# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7cf9a161d7ffd71468abb346c77a05ea"
name = "cycology-custom-discount"
application_url = "https://cycology-custom-discount-code-remix.vercel.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/app/order-paid"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_products,write_discounts,write_products,read_orders"

[auth]
redirect_urls = [
  "https://cycology-custom-discount-code-remix.vercel.app/api/auth"
]
